[package]
name = "post-killer-ffi-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
post-killer-domain = { path = "../domain" }
post-killer-application = { path = "../application" }
post-killer-http-engine = { path = "../http_engine" }
