// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1701565116;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__execute_request_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "execute_request",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::FfiRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok =
                            Ok::<_, ()>(crate::api::execute_request(api_request).await)?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__execute_request_with_options_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "execute_request_with_options",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::FfiRequest>::sse_decode(&mut deserializer);
            let api_options = <crate::api::FfiExecutionOptions>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Ok::<_, ()>(
                            crate::api::execute_request_with_options(api_request, api_options)
                                .await,
                        )?;
                        std::result::Result::Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__ffi_execution_options_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_execution_options_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::FfiExecutionOptions::default())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::FfiApiKeyPlacement {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::FfiApiKeyPlacement::Header,
            1 => crate::api::FfiApiKeyPlacement::Query,
            _ => unreachable!("Invalid variant for FfiApiKeyPlacement: {}", inner),
        };
    }
}

impl SseDecode for crate::api::FfiExecutionError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::FfiExecutionErrorKind>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_field = <Option<String>>::sse_decode(deserializer);
        let mut var_limitBytes = <Option<u64>>::sse_decode(deserializer);
        return crate::api::FfiExecutionError {
            kind: var_kind,
            message: var_message,
            field: var_field,
            limit_bytes: var_limitBytes,
        };
    }
}

impl SseDecode for crate::api::FfiExecutionErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::FfiExecutionErrorKind::InvalidRequest,
            1 => crate::api::FfiExecutionErrorKind::InvalidJsonBody,
            2 => crate::api::FfiExecutionErrorKind::InvalidUrl,
            3 => crate::api::FfiExecutionErrorKind::InvalidHeaderName,
            4 => crate::api::FfiExecutionErrorKind::InvalidHeaderValue,
            5 => crate::api::FfiExecutionErrorKind::UnsupportedBody,
            6 => crate::api::FfiExecutionErrorKind::Timeout,
            7 => crate::api::FfiExecutionErrorKind::Cancelled,
            8 => crate::api::FfiExecutionErrorKind::TransportConnect,
            9 => crate::api::FfiExecutionErrorKind::TransportRequest,
            10 => crate::api::FfiExecutionErrorKind::TransportDecode,
            11 => crate::api::FfiExecutionErrorKind::TransportOther,
            12 => crate::api::FfiExecutionErrorKind::ResponseTooLarge,
            13 => crate::api::FfiExecutionErrorKind::Internal,
            _ => unreachable!("Invalid variant for FfiExecutionErrorKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::FfiExecutionOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timeoutMillis = <u64>::sse_decode(deserializer);
        let mut var_maxRedirects = <Option<u32>>::sse_decode(deserializer);
        let mut var_maxResponseBytes = <u64>::sse_decode(deserializer);
        return crate::api::FfiExecutionOptions {
            timeout_millis: var_timeoutMillis,
            max_redirects: var_maxRedirects,
            max_response_bytes: var_maxResponseBytes,
        };
    }
}

impl SseDecode for crate::api::FfiExecutionOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_response = <Option<crate::api::FfiExecutionResponse>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::api::FfiExecutionError>>::sse_decode(deserializer);
        return crate::api::FfiExecutionOutcome {
            response: var_response,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::FfiExecutionResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_requestId = <String>::sse_decode(deserializer);
        let mut var_status = <u16>::sse_decode(deserializer);
        let mut var_headers = <Vec<crate::api::FfiResponseHeader>>::sse_decode(deserializer);
        let mut var_body = <Vec<u8>>::sse_decode(deserializer);
        let mut var_effectiveUrl = <String>::sse_decode(deserializer);
        let mut var_durationMillis = <u64>::sse_decode(deserializer);
        return crate::api::FfiExecutionResponse {
            request_id: var_requestId,
            status: var_status,
            headers: var_headers,
            body: var_body,
            effective_url: var_effectiveUrl,
            duration_millis: var_durationMillis,
        };
    }
}

impl SseDecode for crate::api::FfiKeyValue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_key = <String>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        let mut var_enabled = <bool>::sse_decode(deserializer);
        return crate::api::FfiKeyValue {
            key: var_key,
            value: var_value,
            enabled: var_enabled,
        };
    }
}

impl SseDecode for crate::api::FfiRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_method = <crate::api::FfiRequestMethod>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_queryParams = <Vec<crate::api::FfiKeyValue>>::sse_decode(deserializer);
        let mut var_headers = <Vec<crate::api::FfiKeyValue>>::sse_decode(deserializer);
        let mut var_body = <crate::api::FfiRequestBody>::sse_decode(deserializer);
        let mut var_auth = <crate::api::FfiRequestAuth>::sse_decode(deserializer);
        return crate::api::FfiRequest {
            id: var_id,
            name: var_name,
            method: var_method,
            url: var_url,
            query_params: var_queryParams,
            headers: var_headers,
            body: var_body,
            auth: var_auth,
        };
    }
}

impl SseDecode for crate::api::FfiRequestAuth {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::FfiRequestAuthKind>::sse_decode(deserializer);
        let mut var_username = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_token = <String>::sse_decode(deserializer);
        let mut var_key = <String>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        let mut var_placement = <crate::api::FfiApiKeyPlacement>::sse_decode(deserializer);
        return crate::api::FfiRequestAuth {
            kind: var_kind,
            username: var_username,
            password: var_password,
            token: var_token,
            key: var_key,
            value: var_value,
            placement: var_placement,
        };
    }
}

impl SseDecode for crate::api::FfiRequestAuthKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::FfiRequestAuthKind::None,
            1 => crate::api::FfiRequestAuthKind::Basic,
            2 => crate::api::FfiRequestAuthKind::Bearer,
            3 => crate::api::FfiRequestAuthKind::ApiKey,
            _ => unreachable!("Invalid variant for FfiRequestAuthKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::FfiRequestBody {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::FfiRequestBodyKind>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_contentType = <Option<String>>::sse_decode(deserializer);
        let mut var_fields = <Vec<crate::api::FfiKeyValue>>::sse_decode(deserializer);
        return crate::api::FfiRequestBody {
            kind: var_kind,
            content: var_content,
            content_type: var_contentType,
            fields: var_fields,
        };
    }
}

impl SseDecode for crate::api::FfiRequestBodyKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::FfiRequestBodyKind::Empty,
            1 => crate::api::FfiRequestBodyKind::Text,
            2 => crate::api::FfiRequestBodyKind::Json,
            3 => crate::api::FfiRequestBodyKind::FormUrlEncoded,
            4 => crate::api::FfiRequestBodyKind::Multipart,
            _ => unreachable!("Invalid variant for FfiRequestBodyKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::FfiRequestMethod {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::FfiRequestMethod::Get,
            1 => crate::api::FfiRequestMethod::Post,
            2 => crate::api::FfiRequestMethod::Put,
            3 => crate::api::FfiRequestMethod::Patch,
            4 => crate::api::FfiRequestMethod::Delete,
            5 => crate::api::FfiRequestMethod::Head,
            6 => crate::api::FfiRequestMethod::Options,
            _ => unreachable!("Invalid variant for FfiRequestMethod: {}", inner),
        };
    }
}

impl SseDecode for crate::api::FfiResponseHeader {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_value = <Vec<u8>>::sse_decode(deserializer);
        return crate::api::FfiResponseHeader {
            name: var_name,
            value: var_value,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::FfiKeyValue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FfiKeyValue>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::FfiResponseHeader> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FfiResponseHeader>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::FfiExecutionError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::FfiExecutionError>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::FfiExecutionResponse> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::FfiExecutionResponse>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__execute_request_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__execute_request_with_options_impl(port, ptr, rust_vec_len, data_len),
        3 => {
            wire__crate__api__ffi_execution_options_default_impl(port, ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiApiKeyPlacement {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Header => 0.into_dart(),
            Self::Query => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiApiKeyPlacement
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiApiKeyPlacement>
    for crate::api::FfiApiKeyPlacement
{
    fn into_into_dart(self) -> crate::api::FfiApiKeyPlacement {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiExecutionError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.field.into_into_dart().into_dart(),
            self.limit_bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiExecutionError {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiExecutionError>
    for crate::api::FfiExecutionError
{
    fn into_into_dart(self) -> crate::api::FfiExecutionError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiExecutionErrorKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidRequest => 0.into_dart(),
            Self::InvalidJsonBody => 1.into_dart(),
            Self::InvalidUrl => 2.into_dart(),
            Self::InvalidHeaderName => 3.into_dart(),
            Self::InvalidHeaderValue => 4.into_dart(),
            Self::UnsupportedBody => 5.into_dart(),
            Self::Timeout => 6.into_dart(),
            Self::Cancelled => 7.into_dart(),
            Self::TransportConnect => 8.into_dart(),
            Self::TransportRequest => 9.into_dart(),
            Self::TransportDecode => 10.into_dart(),
            Self::TransportOther => 11.into_dart(),
            Self::ResponseTooLarge => 12.into_dart(),
            Self::Internal => 13.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiExecutionErrorKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiExecutionErrorKind>
    for crate::api::FfiExecutionErrorKind
{
    fn into_into_dart(self) -> crate::api::FfiExecutionErrorKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiExecutionOptions {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.timeout_millis.into_into_dart().into_dart(),
            self.max_redirects.into_into_dart().into_dart(),
            self.max_response_bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiExecutionOptions
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiExecutionOptions>
    for crate::api::FfiExecutionOptions
{
    fn into_into_dart(self) -> crate::api::FfiExecutionOptions {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiExecutionOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.response.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiExecutionOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiExecutionOutcome>
    for crate::api::FfiExecutionOutcome
{
    fn into_into_dart(self) -> crate::api::FfiExecutionOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiExecutionResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.request_id.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.headers.into_into_dart().into_dart(),
            self.body.into_into_dart().into_dart(),
            self.effective_url.into_into_dart().into_dart(),
            self.duration_millis.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiExecutionResponse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiExecutionResponse>
    for crate::api::FfiExecutionResponse
{
    fn into_into_dart(self) -> crate::api::FfiExecutionResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiKeyValue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.enabled.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiKeyValue {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiKeyValue> for crate::api::FfiKeyValue {
    fn into_into_dart(self) -> crate::api::FfiKeyValue {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.method.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.query_params.into_into_dart().into_dart(),
            self.headers.into_into_dart().into_dart(),
            self.body.into_into_dart().into_dart(),
            self.auth.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiRequest {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiRequest> for crate::api::FfiRequest {
    fn into_into_dart(self) -> crate::api::FfiRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiRequestAuth {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.username.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
            self.token.into_into_dart().into_dart(),
            self.key.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.placement.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiRequestAuth {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiRequestAuth> for crate::api::FfiRequestAuth {
    fn into_into_dart(self) -> crate::api::FfiRequestAuth {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiRequestAuthKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::None => 0.into_dart(),
            Self::Basic => 1.into_dart(),
            Self::Bearer => 2.into_dart(),
            Self::ApiKey => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiRequestAuthKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiRequestAuthKind>
    for crate::api::FfiRequestAuthKind
{
    fn into_into_dart(self) -> crate::api::FfiRequestAuthKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiRequestBody {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.content_type.into_into_dart().into_dart(),
            self.fields.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiRequestBody {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiRequestBody> for crate::api::FfiRequestBody {
    fn into_into_dart(self) -> crate::api::FfiRequestBody {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiRequestBodyKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Empty => 0.into_dart(),
            Self::Text => 1.into_dart(),
            Self::Json => 2.into_dart(),
            Self::FormUrlEncoded => 3.into_dart(),
            Self::Multipart => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::FfiRequestBodyKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiRequestBodyKind>
    for crate::api::FfiRequestBodyKind
{
    fn into_into_dart(self) -> crate::api::FfiRequestBodyKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiRequestMethod {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Get => 0.into_dart(),
            Self::Post => 1.into_dart(),
            Self::Put => 2.into_dart(),
            Self::Patch => 3.into_dart(),
            Self::Delete => 4.into_dart(),
            Self::Head => 5.into_dart(),
            Self::Options => 6.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiRequestMethod {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiRequestMethod>
    for crate::api::FfiRequestMethod
{
    fn into_into_dart(self) -> crate::api::FfiRequestMethod {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FfiResponseHeader {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FfiResponseHeader {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FfiResponseHeader>
    for crate::api::FfiResponseHeader
{
    fn into_into_dart(self) -> crate::api::FfiResponseHeader {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::FfiApiKeyPlacement {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::FfiApiKeyPlacement::Header => 0,
                crate::api::FfiApiKeyPlacement::Query => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::FfiExecutionError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::FfiExecutionErrorKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.message, serializer);
        <Option<String>>::sse_encode(self.field, serializer);
        <Option<u64>>::sse_encode(self.limit_bytes, serializer);
    }
}

impl SseEncode for crate::api::FfiExecutionErrorKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::FfiExecutionErrorKind::InvalidRequest => 0,
                crate::api::FfiExecutionErrorKind::InvalidJsonBody => 1,
                crate::api::FfiExecutionErrorKind::InvalidUrl => 2,
                crate::api::FfiExecutionErrorKind::InvalidHeaderName => 3,
                crate::api::FfiExecutionErrorKind::InvalidHeaderValue => 4,
                crate::api::FfiExecutionErrorKind::UnsupportedBody => 5,
                crate::api::FfiExecutionErrorKind::Timeout => 6,
                crate::api::FfiExecutionErrorKind::Cancelled => 7,
                crate::api::FfiExecutionErrorKind::TransportConnect => 8,
                crate::api::FfiExecutionErrorKind::TransportRequest => 9,
                crate::api::FfiExecutionErrorKind::TransportDecode => 10,
                crate::api::FfiExecutionErrorKind::TransportOther => 11,
                crate::api::FfiExecutionErrorKind::ResponseTooLarge => 12,
                crate::api::FfiExecutionErrorKind::Internal => 13,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::FfiExecutionOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.timeout_millis, serializer);
        <Option<u32>>::sse_encode(self.max_redirects, serializer);
        <u64>::sse_encode(self.max_response_bytes, serializer);
    }
}

impl SseEncode for crate::api::FfiExecutionOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::api::FfiExecutionResponse>>::sse_encode(self.response, serializer);
        <Option<crate::api::FfiExecutionError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::FfiExecutionResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.request_id, serializer);
        <u16>::sse_encode(self.status, serializer);
        <Vec<crate::api::FfiResponseHeader>>::sse_encode(self.headers, serializer);
        <Vec<u8>>::sse_encode(self.body, serializer);
        <String>::sse_encode(self.effective_url, serializer);
        <u64>::sse_encode(self.duration_millis, serializer);
    }
}

impl SseEncode for crate::api::FfiKeyValue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key, serializer);
        <String>::sse_encode(self.value, serializer);
        <bool>::sse_encode(self.enabled, serializer);
    }
}

impl SseEncode for crate::api::FfiRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <crate::api::FfiRequestMethod>::sse_encode(self.method, serializer);
        <String>::sse_encode(self.url, serializer);
        <Vec<crate::api::FfiKeyValue>>::sse_encode(self.query_params, serializer);
        <Vec<crate::api::FfiKeyValue>>::sse_encode(self.headers, serializer);
        <crate::api::FfiRequestBody>::sse_encode(self.body, serializer);
        <crate::api::FfiRequestAuth>::sse_encode(self.auth, serializer);
    }
}

impl SseEncode for crate::api::FfiRequestAuth {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::FfiRequestAuthKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.username, serializer);
        <String>::sse_encode(self.password, serializer);
        <String>::sse_encode(self.token, serializer);
        <String>::sse_encode(self.key, serializer);
        <String>::sse_encode(self.value, serializer);
        <crate::api::FfiApiKeyPlacement>::sse_encode(self.placement, serializer);
    }
}

impl SseEncode for crate::api::FfiRequestAuthKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::FfiRequestAuthKind::None => 0,
                crate::api::FfiRequestAuthKind::Basic => 1,
                crate::api::FfiRequestAuthKind::Bearer => 2,
                crate::api::FfiRequestAuthKind::ApiKey => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::FfiRequestBody {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::FfiRequestBodyKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.content, serializer);
        <Option<String>>::sse_encode(self.content_type, serializer);
        <Vec<crate::api::FfiKeyValue>>::sse_encode(self.fields, serializer);
    }
}

impl SseEncode for crate::api::FfiRequestBodyKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::FfiRequestBodyKind::Empty => 0,
                crate::api::FfiRequestBodyKind::Text => 1,
                crate::api::FfiRequestBodyKind::Json => 2,
                crate::api::FfiRequestBodyKind::FormUrlEncoded => 3,
                crate::api::FfiRequestBodyKind::Multipart => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::FfiRequestMethod {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::FfiRequestMethod::Get => 0,
                crate::api::FfiRequestMethod::Post => 1,
                crate::api::FfiRequestMethod::Put => 2,
                crate::api::FfiRequestMethod::Patch => 3,
                crate::api::FfiRequestMethod::Delete => 4,
                crate::api::FfiRequestMethod::Head => 5,
                crate::api::FfiRequestMethod::Options => 6,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::FfiResponseHeader {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <Vec<u8>>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::FfiKeyValue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FfiKeyValue>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::FfiResponseHeader> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FfiResponseHeader>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::FfiExecutionError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::FfiExecutionError>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::FfiExecutionResponse> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::FfiExecutionResponse>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
