// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_data_directory`, `error`, `next_id`, `success`, `with_storage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Lists persisted local workspaces. The database is owned exclusively by the
/// Rust storage adapter; Flutter only receives owned DTOs through FRB.
Future<List<FfiWorkspace>> listWorkspaces() =>
    PostKillerRustLib.instance.api.crateApiListWorkspaces();

Future<FfiWorkspace> createWorkspace({required String name}) =>
    PostKillerRustLib.instance.api.crateApiCreateWorkspace(name: name);

/// Deletes a workspace and all of its local collections, requests and
/// environments through the database's foreign-key cascade.
Future<void> deleteWorkspace({required String id}) =>
    PostKillerRustLib.instance.api.crateApiDeleteWorkspace(id: id);

Future<List<FfiCollection>> listCollections({required String workspaceId}) =>
    PostKillerRustLib.instance.api.crateApiListCollections(
      workspaceId: workspaceId,
    );

Future<FfiCollection> createCollection({
  required String workspaceId,
  required String name,
}) => PostKillerRustLib.instance.api.crateApiCreateCollection(
  workspaceId: workspaceId,
  name: name,
);

/// Deletes a collection and all saved requests in it.
Future<void> deleteCollection({required String id}) =>
    PostKillerRustLib.instance.api.crateApiDeleteCollection(id: id);

/// Lists environment profiles stored locally for one workspace. Values are
/// returned only to the local Flutter process and never added to history.
Future<List<FfiEnvironment>> listEnvironments({required String workspaceId}) =>
    PostKillerRustLib.instance.api.crateApiListEnvironments(
      workspaceId: workspaceId,
    );

Future<FfiEnvironment> createEnvironment({
  required String workspaceId,
  required String name,
}) => PostKillerRustLib.instance.api.crateApiCreateEnvironment(
  workspaceId: workspaceId,
  name: name,
);

Future<void> deleteEnvironment({required String id}) =>
    PostKillerRustLib.instance.api.crateApiDeleteEnvironment(id: id);

Future<List<FfiEnvironmentVariable>> listEnvironmentVariables({
  required String environmentId,
}) => PostKillerRustLib.instance.api.crateApiListEnvironmentVariables(
  environmentId: environmentId,
);

Future<FfiEnvironmentVariable> saveEnvironmentVariable({
  required FfiEnvironmentVariable variable,
}) => PostKillerRustLib.instance.api.crateApiSaveEnvironmentVariable(
  variable: variable,
);

Future<void> deleteEnvironmentVariable({required String id}) =>
    PostKillerRustLib.instance.api.crateApiDeleteEnvironmentVariable(id: id);

Future<List<FfiStoredRequest>> listRequests({required String collectionId}) =>
    PostKillerRustLib.instance.api.crateApiListRequests(
      collectionId: collectionId,
    );

/// Deletes one saved request. Its local execution history is cascaded too.
Future<void> deleteRequest({required String id}) =>
    PostKillerRustLib.instance.api.crateApiDeleteRequest(id: id);

/// Records only sanitized execution metadata for a saved request. Drafts are
/// intentionally never accepted by storage because they have no persisted ID.
Future<void> saveExecutionHistory({
  required FfiExecutionHistoryRecord record,
}) =>
    PostKillerRustLib.instance.api.crateApiSaveExecutionHistory(record: record);

/// Returns workspace-wide execution metadata, newest first. The bridge never
/// returns request content, URL or any authentication material here.
Future<List<FfiExecutionHistoryRecord>> listWorkspaceExecutionHistory({
  required String workspaceId,
}) => PostKillerRustLib.instance.api.crateApiListWorkspaceExecutionHistory(
  workspaceId: workspaceId,
);

Future<int> clearWorkspaceExecutionHistory({required String workspaceId}) =>
    PostKillerRustLib.instance.api.crateApiClearWorkspaceExecutionHistory(
      workspaceId: workspaceId,
    );

/// Creates or updates a request in the selected collection/folder.
Future<FfiStoredRequest> saveRequest({
  required String collectionId,
  String? folderId,
  required FfiRequest request,
}) => PostKillerRustLib.instance.api.crateApiSaveRequest(
  collectionId: collectionId,
  folderId: folderId,
  request: request,
);

/// Executes a request using conservative transport defaults. FRB maps this
/// `async fn` to a Dart `Future<FfiExecutionOutcome>`.
Future<FfiExecutionOutcome> executeRequest({required FfiRequest request}) =>
    PostKillerRustLib.instance.api.crateApiExecuteRequest(request: request);

/// Executes a request after resolving enabled variables from the selected local
/// environment. Resolution is pure: neither the stored request nor the
/// environment values are written into execution history or diagnostic output.
Future<FfiExecutionOutcome> executeRequestWithVariables({
  required FfiRequest request,
  required List<FfiKeyValue> variables,
}) => PostKillerRustLib.instance.api.crateApiExecuteRequestWithVariables(
  request: request,
  variables: variables,
);

/// Executes with caller-controlled limits while retaining typed outcomes for
/// expected validation and transport failures.
Future<FfiExecutionOutcome> executeRequestWithOptions({
  required FfiRequest request,
  required FfiExecutionOptions options,
}) => PostKillerRustLib.instance.api.crateApiExecuteRequestWithOptions(
  request: request,
  options: options,
);

enum FfiApiKeyPlacement { header, query }

class FfiCollection {
  final String id;
  final String workspaceId;
  final String name;

  const FfiCollection({
    required this.id,
    required this.workspaceId,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ workspaceId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCollection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          name == other.name;
}

class FfiEnvironment {
  final String id;
  final String workspaceId;
  final String name;

  const FfiEnvironment({
    required this.id,
    required this.workspaceId,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ workspaceId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiEnvironment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          name == other.name;
}

class FfiEnvironmentVariable {
  final String id;
  final String environmentId;
  final String key;
  final String value;
  final bool enabled;

  const FfiEnvironmentVariable({
    required this.id,
    required this.environmentId,
    required this.key,
    required this.value,
    required this.enabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      environmentId.hashCode ^
      key.hashCode ^
      value.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiEnvironmentVariable &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          environmentId == other.environmentId &&
          key == other.key &&
          value == other.value &&
          enabled == other.enabled;
}

class FfiExecutionError {
  final FfiExecutionErrorKind kind;

  /// Privacy-safe user-facing summary; it never contains request credentials or body.
  final String message;

  /// Optional editor field to focus, such as `url`, `header`, or `body`.
  final String? field;
  final int? limitBytes;

  const FfiExecutionError({
    required this.kind,
    required this.message,
    this.field,
    this.limitBytes,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ message.hashCode ^ field.hashCode ^ limitBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          field == other.field &&
          limitBytes == other.limitBytes;
}

enum FfiExecutionErrorKind {
  invalidRequest,
  invalidJsonBody,
  invalidUrl,
  invalidHeaderName,
  invalidHeaderValue,
  unsupportedBody,
  timeout,
  cancelled,
  transportConnect,
  transportRequest,
  transportDecode,
  transportOther,
  responseTooLarge,
  internal,
}

enum FfiExecutionHistoryErrorCategory {
  timeout,
  dns,
  connection,
  tls,
  proxy,
  redirect,
  requestBody,
  responseBody,
  other,
}

/// Privacy-safe execution metadata. It intentionally has no URL, request or
/// response body, headers, cookies, credentials or raw error text.
class FfiExecutionHistoryRecord {
  final String executionId;
  final String requestId;
  final int executedAtUnixMs;
  final int? statusCode;
  final int durationMs;
  final int responseSizeBytes;
  final FfiExecutionHistoryResultKind resultKind;
  final FfiExecutionHistoryErrorCategory? errorCategory;

  const FfiExecutionHistoryRecord({
    required this.executionId,
    required this.requestId,
    required this.executedAtUnixMs,
    this.statusCode,
    required this.durationMs,
    required this.responseSizeBytes,
    required this.resultKind,
    this.errorCategory,
  });

  @override
  int get hashCode =>
      executionId.hashCode ^
      requestId.hashCode ^
      executedAtUnixMs.hashCode ^
      statusCode.hashCode ^
      durationMs.hashCode ^
      responseSizeBytes.hashCode ^
      resultKind.hashCode ^
      errorCategory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionHistoryRecord &&
          runtimeType == other.runtimeType &&
          executionId == other.executionId &&
          requestId == other.requestId &&
          executedAtUnixMs == other.executedAtUnixMs &&
          statusCode == other.statusCode &&
          durationMs == other.durationMs &&
          responseSizeBytes == other.responseSizeBytes &&
          resultKind == other.resultKind &&
          errorCategory == other.errorCategory;
}

enum FfiExecutionHistoryResultKind { response, error, cancelled }

class FfiExecutionOptions {
  final int timeoutMillis;

  /// `None` disables redirects; otherwise this is the maximum followed count.
  final int? maxRedirects;
  final int maxResponseBytes;

  const FfiExecutionOptions({
    required this.timeoutMillis,
    this.maxRedirects,
    required this.maxResponseBytes,
  });

  static Future<FfiExecutionOptions> default_() =>
      PostKillerRustLib.instance.api.crateApiFfiExecutionOptionsDefault();

  @override
  int get hashCode =>
      timeoutMillis.hashCode ^
      maxRedirects.hashCode ^
      maxResponseBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionOptions &&
          runtimeType == other.runtimeType &&
          timeoutMillis == other.timeoutMillis &&
          maxRedirects == other.maxRedirects &&
          maxResponseBytes == other.maxResponseBytes;
}

/// Exactly one of `response` and `error` is populated.
class FfiExecutionOutcome {
  final FfiExecutionResponse? response;
  final FfiExecutionError? error;

  const FfiExecutionOutcome({this.response, this.error});

  @override
  int get hashCode => response.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionOutcome &&
          runtimeType == other.runtimeType &&
          response == other.response &&
          error == other.error;
}

class FfiExecutionResponse {
  final String requestId;
  final int status;
  final List<FfiResponseHeader> headers;
  final Uint8List body;
  final String effectiveUrl;
  final int durationMillis;

  const FfiExecutionResponse({
    required this.requestId,
    required this.status,
    required this.headers,
    required this.body,
    required this.effectiveUrl,
    required this.durationMillis,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      status.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      effectiveUrl.hashCode ^
      durationMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionResponse &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          status == other.status &&
          headers == other.headers &&
          body == other.body &&
          effectiveUrl == other.effectiveUrl &&
          durationMillis == other.durationMillis;
}

class FfiKeyValue {
  final String key;
  final String value;
  final bool enabled;

  const FfiKeyValue({
    required this.key,
    required this.value,
    required this.enabled,
  });

  @override
  int get hashCode => key.hashCode ^ value.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiKeyValue &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value &&
          enabled == other.enabled;
}

class FfiRequest {
  final String id;
  final String name;
  final FfiRequestMethod method;
  final String url;
  final List<FfiKeyValue> queryParams;
  final List<FfiKeyValue> headers;
  final FfiRequestBody body;
  final FfiRequestAuth auth;

  const FfiRequest({
    required this.id,
    required this.name,
    required this.method,
    required this.url,
    required this.queryParams,
    required this.headers,
    required this.body,
    required this.auth,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      method.hashCode ^
      url.hashCode ^
      queryParams.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      auth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRequest &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          method == other.method &&
          url == other.url &&
          queryParams == other.queryParams &&
          headers == other.headers &&
          body == other.body &&
          auth == other.auth;
}

/// Credentials are deliberately input-only. They are never copied into an
/// execution response or error.
class FfiRequestAuth {
  final FfiRequestAuthKind kind;
  final String username;
  final String password;
  final String token;
  final String key;
  final String value;
  final FfiApiKeyPlacement placement;

  const FfiRequestAuth({
    required this.kind,
    required this.username,
    required this.password,
    required this.token,
    required this.key,
    required this.value,
    required this.placement,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      username.hashCode ^
      password.hashCode ^
      token.hashCode ^
      key.hashCode ^
      value.hashCode ^
      placement.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRequestAuth &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          username == other.username &&
          password == other.password &&
          token == other.token &&
          key == other.key &&
          value == other.value &&
          placement == other.placement;
}

enum FfiRequestAuthKind { none, basic, bearer, apiKey }

/// Flat body DTO keeps every Dart-facing field simple. Fields irrelevant to
/// `kind` are ignored during conversion.
class FfiRequestBody {
  final FfiRequestBodyKind kind;
  final String content;
  final String? contentType;
  final List<FfiKeyValue> fields;

  const FfiRequestBody({
    required this.kind,
    required this.content,
    this.contentType,
    required this.fields,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ content.hashCode ^ contentType.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRequestBody &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          content == other.content &&
          contentType == other.contentType &&
          fields == other.fields;
}

enum FfiRequestBodyKind { empty, text, json, formUrlEncoded, multipart }

enum FfiRequestMethod { get_, post, put, patch, delete, head, options }

class FfiResponseHeader {
  final String name;
  final Uint8List value;

  const FfiResponseHeader({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiResponseHeader &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

/// A complete saved request. Keeping the collection association alongside the
/// request lets Flutter show a saved request in its folder and reopen it with
/// all fields intact.
class FfiStoredRequest {
  final String collectionId;
  final String? folderId;
  final FfiRequest request;

  const FfiStoredRequest({
    required this.collectionId,
    this.folderId,
    required this.request,
  });

  @override
  int get hashCode =>
      collectionId.hashCode ^ folderId.hashCode ^ request.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiStoredRequest &&
          runtimeType == other.runtimeType &&
          collectionId == other.collectionId &&
          folderId == other.folderId &&
          request == other.request;
}

class FfiWorkspace {
  final String id;
  final String name;

  const FfiWorkspace({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiWorkspace &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
