// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_data_directory`, `error`, `next_id`, `success`, `with_storage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Lists persisted local workspaces. The database is owned exclusively by the
/// Rust storage adapter; Flutter only receives owned DTOs through FRB.
Future<List<FfiWorkspace>> listWorkspaces() =>
    PostKillerRustLib.instance.api.crateApiListWorkspaces();

Future<FfiWorkspace> createWorkspace({required String name}) =>
    PostKillerRustLib.instance.api.crateApiCreateWorkspace(name: name);

Future<List<FfiCollection>> listCollections({required String workspaceId}) =>
    PostKillerRustLib.instance.api.crateApiListCollections(
      workspaceId: workspaceId,
    );

Future<FfiCollection> createCollection({
  required String workspaceId,
  required String name,
}) => PostKillerRustLib.instance.api.crateApiCreateCollection(
  workspaceId: workspaceId,
  name: name,
);

Future<List<FfiStoredRequest>> listRequests({required String collectionId}) =>
    PostKillerRustLib.instance.api.crateApiListRequests(
      collectionId: collectionId,
    );

/// Creates or updates a request in the selected collection/folder.
Future<FfiStoredRequest> saveRequest({
  required String collectionId,
  String? folderId,
  required FfiRequest request,
}) => PostKillerRustLib.instance.api.crateApiSaveRequest(
  collectionId: collectionId,
  folderId: folderId,
  request: request,
);

/// Executes a request using conservative transport defaults. FRB maps this
/// `async fn` to a Dart `Future<FfiExecutionOutcome>`.
Future<FfiExecutionOutcome> executeRequest({required FfiRequest request}) =>
    PostKillerRustLib.instance.api.crateApiExecuteRequest(request: request);

/// Executes with caller-controlled limits while retaining typed outcomes for
/// expected validation and transport failures.
Future<FfiExecutionOutcome> executeRequestWithOptions({
  required FfiRequest request,
  required FfiExecutionOptions options,
}) => PostKillerRustLib.instance.api.crateApiExecuteRequestWithOptions(
  request: request,
  options: options,
);

enum FfiApiKeyPlacement { header, query }

class FfiCollection {
  final String id;
  final String workspaceId;
  final String name;

  const FfiCollection({
    required this.id,
    required this.workspaceId,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ workspaceId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiCollection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          workspaceId == other.workspaceId &&
          name == other.name;
}

class FfiExecutionError {
  final FfiExecutionErrorKind kind;

  /// Privacy-safe user-facing summary; it never contains request credentials or body.
  final String message;

  /// Optional editor field to focus, such as `url`, `header`, or `body`.
  final String? field;
  final int? limitBytes;

  const FfiExecutionError({
    required this.kind,
    required this.message,
    this.field,
    this.limitBytes,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ message.hashCode ^ field.hashCode ^ limitBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          field == other.field &&
          limitBytes == other.limitBytes;
}

enum FfiExecutionErrorKind {
  invalidRequest,
  invalidJsonBody,
  invalidUrl,
  invalidHeaderName,
  invalidHeaderValue,
  unsupportedBody,
  timeout,
  cancelled,
  transportConnect,
  transportRequest,
  transportDecode,
  transportOther,
  responseTooLarge,
  internal,
}

class FfiExecutionOptions {
  final int timeoutMillis;

  /// `None` disables redirects; otherwise this is the maximum followed count.
  final int? maxRedirects;
  final int maxResponseBytes;

  const FfiExecutionOptions({
    required this.timeoutMillis,
    this.maxRedirects,
    required this.maxResponseBytes,
  });

  static Future<FfiExecutionOptions> default_() =>
      PostKillerRustLib.instance.api.crateApiFfiExecutionOptionsDefault();

  @override
  int get hashCode =>
      timeoutMillis.hashCode ^
      maxRedirects.hashCode ^
      maxResponseBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionOptions &&
          runtimeType == other.runtimeType &&
          timeoutMillis == other.timeoutMillis &&
          maxRedirects == other.maxRedirects &&
          maxResponseBytes == other.maxResponseBytes;
}

/// Exactly one of `response` and `error` is populated.
class FfiExecutionOutcome {
  final FfiExecutionResponse? response;
  final FfiExecutionError? error;

  const FfiExecutionOutcome({this.response, this.error});

  @override
  int get hashCode => response.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionOutcome &&
          runtimeType == other.runtimeType &&
          response == other.response &&
          error == other.error;
}

class FfiExecutionResponse {
  final String requestId;
  final int status;
  final List<FfiResponseHeader> headers;
  final Uint8List body;
  final String effectiveUrl;
  final int durationMillis;

  const FfiExecutionResponse({
    required this.requestId,
    required this.status,
    required this.headers,
    required this.body,
    required this.effectiveUrl,
    required this.durationMillis,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      status.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      effectiveUrl.hashCode ^
      durationMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiExecutionResponse &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          status == other.status &&
          headers == other.headers &&
          body == other.body &&
          effectiveUrl == other.effectiveUrl &&
          durationMillis == other.durationMillis;
}

class FfiKeyValue {
  final String key;
  final String value;
  final bool enabled;

  const FfiKeyValue({
    required this.key,
    required this.value,
    required this.enabled,
  });

  @override
  int get hashCode => key.hashCode ^ value.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiKeyValue &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value &&
          enabled == other.enabled;
}

class FfiRequest {
  final String id;
  final String name;
  final FfiRequestMethod method;
  final String url;
  final List<FfiKeyValue> queryParams;
  final List<FfiKeyValue> headers;
  final FfiRequestBody body;
  final FfiRequestAuth auth;

  const FfiRequest({
    required this.id,
    required this.name,
    required this.method,
    required this.url,
    required this.queryParams,
    required this.headers,
    required this.body,
    required this.auth,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      method.hashCode ^
      url.hashCode ^
      queryParams.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      auth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRequest &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          method == other.method &&
          url == other.url &&
          queryParams == other.queryParams &&
          headers == other.headers &&
          body == other.body &&
          auth == other.auth;
}

/// Credentials are deliberately input-only. They are never copied into an
/// execution response or error.
class FfiRequestAuth {
  final FfiRequestAuthKind kind;
  final String username;
  final String password;
  final String token;
  final String key;
  final String value;
  final FfiApiKeyPlacement placement;

  const FfiRequestAuth({
    required this.kind,
    required this.username,
    required this.password,
    required this.token,
    required this.key,
    required this.value,
    required this.placement,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      username.hashCode ^
      password.hashCode ^
      token.hashCode ^
      key.hashCode ^
      value.hashCode ^
      placement.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRequestAuth &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          username == other.username &&
          password == other.password &&
          token == other.token &&
          key == other.key &&
          value == other.value &&
          placement == other.placement;
}

enum FfiRequestAuthKind { none, basic, bearer, apiKey }

/// Flat body DTO keeps every Dart-facing field simple. Fields irrelevant to
/// `kind` are ignored during conversion.
class FfiRequestBody {
  final FfiRequestBodyKind kind;
  final String content;
  final String? contentType;
  final List<FfiKeyValue> fields;

  const FfiRequestBody({
    required this.kind,
    required this.content,
    this.contentType,
    required this.fields,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ content.hashCode ^ contentType.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRequestBody &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          content == other.content &&
          contentType == other.contentType &&
          fields == other.fields;
}

enum FfiRequestBodyKind { empty, text, json, formUrlEncoded, multipart }

enum FfiRequestMethod { get_, post, put, patch, delete, head, options }

class FfiResponseHeader {
  final String name;
  final Uint8List value;

  const FfiResponseHeader({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiResponseHeader &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

/// A complete saved request. Keeping the collection association alongside the
/// request lets Flutter show a saved request in its folder and reopen it with
/// all fields intact.
class FfiStoredRequest {
  final String collectionId;
  final String? folderId;
  final FfiRequest request;

  const FfiStoredRequest({
    required this.collectionId,
    this.folderId,
    required this.request,
  });

  @override
  int get hashCode =>
      collectionId.hashCode ^ folderId.hashCode ^ request.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiStoredRequest &&
          runtimeType == other.runtimeType &&
          collectionId == other.collectionId &&
          folderId == other.folderId &&
          request == other.request;
}

class FfiWorkspace {
  final String id;
  final String name;

  const FfiWorkspace({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiWorkspace &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
