// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class PostKillerRustLibApiImplPlatform
    extends BaseApiImpl<PostKillerRustLibWire> {
  PostKillerRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiEnvironmentVariable dco_decode_box_autoadd_ffi_environment_variable(
    dynamic raw,
  );

  @protected
  FfiExecutionError dco_decode_box_autoadd_ffi_execution_error(dynamic raw);

  @protected
  FfiExecutionOptions dco_decode_box_autoadd_ffi_execution_options(dynamic raw);

  @protected
  FfiExecutionResponse dco_decode_box_autoadd_ffi_execution_response(
    dynamic raw,
  );

  @protected
  FfiRequest dco_decode_box_autoadd_ffi_request(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  FfiApiKeyPlacement dco_decode_ffi_api_key_placement(dynamic raw);

  @protected
  FfiCollection dco_decode_ffi_collection(dynamic raw);

  @protected
  FfiEnvironment dco_decode_ffi_environment(dynamic raw);

  @protected
  FfiEnvironmentVariable dco_decode_ffi_environment_variable(dynamic raw);

  @protected
  FfiExecutionError dco_decode_ffi_execution_error(dynamic raw);

  @protected
  FfiExecutionErrorKind dco_decode_ffi_execution_error_kind(dynamic raw);

  @protected
  FfiExecutionOptions dco_decode_ffi_execution_options(dynamic raw);

  @protected
  FfiExecutionOutcome dco_decode_ffi_execution_outcome(dynamic raw);

  @protected
  FfiExecutionResponse dco_decode_ffi_execution_response(dynamic raw);

  @protected
  FfiKeyValue dco_decode_ffi_key_value(dynamic raw);

  @protected
  FfiRequest dco_decode_ffi_request(dynamic raw);

  @protected
  FfiRequestAuth dco_decode_ffi_request_auth(dynamic raw);

  @protected
  FfiRequestAuthKind dco_decode_ffi_request_auth_kind(dynamic raw);

  @protected
  FfiRequestBody dco_decode_ffi_request_body(dynamic raw);

  @protected
  FfiRequestBodyKind dco_decode_ffi_request_body_kind(dynamic raw);

  @protected
  FfiRequestMethod dco_decode_ffi_request_method(dynamic raw);

  @protected
  FfiResponseHeader dco_decode_ffi_response_header(dynamic raw);

  @protected
  FfiStoredRequest dco_decode_ffi_stored_request(dynamic raw);

  @protected
  FfiWorkspace dco_decode_ffi_workspace(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<FfiCollection> dco_decode_list_ffi_collection(dynamic raw);

  @protected
  List<FfiEnvironment> dco_decode_list_ffi_environment(dynamic raw);

  @protected
  List<FfiEnvironmentVariable> dco_decode_list_ffi_environment_variable(
    dynamic raw,
  );

  @protected
  List<FfiKeyValue> dco_decode_list_ffi_key_value(dynamic raw);

  @protected
  List<FfiResponseHeader> dco_decode_list_ffi_response_header(dynamic raw);

  @protected
  List<FfiStoredRequest> dco_decode_list_ffi_stored_request(dynamic raw);

  @protected
  List<FfiWorkspace> dco_decode_list_ffi_workspace(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FfiExecutionError? dco_decode_opt_box_autoadd_ffi_execution_error(
    dynamic raw,
  );

  @protected
  FfiExecutionResponse? dco_decode_opt_box_autoadd_ffi_execution_response(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiEnvironmentVariable sse_decode_box_autoadd_ffi_environment_variable(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionError sse_decode_box_autoadd_ffi_execution_error(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionOptions sse_decode_box_autoadd_ffi_execution_options(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionResponse sse_decode_box_autoadd_ffi_execution_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiRequest sse_decode_box_autoadd_ffi_request(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  FfiApiKeyPlacement sse_decode_ffi_api_key_placement(
    SseDeserializer deserializer,
  );

  @protected
  FfiCollection sse_decode_ffi_collection(SseDeserializer deserializer);

  @protected
  FfiEnvironment sse_decode_ffi_environment(SseDeserializer deserializer);

  @protected
  FfiEnvironmentVariable sse_decode_ffi_environment_variable(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionError sse_decode_ffi_execution_error(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionErrorKind sse_decode_ffi_execution_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionOptions sse_decode_ffi_execution_options(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionOutcome sse_decode_ffi_execution_outcome(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionResponse sse_decode_ffi_execution_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiKeyValue sse_decode_ffi_key_value(SseDeserializer deserializer);

  @protected
  FfiRequest sse_decode_ffi_request(SseDeserializer deserializer);

  @protected
  FfiRequestAuth sse_decode_ffi_request_auth(SseDeserializer deserializer);

  @protected
  FfiRequestAuthKind sse_decode_ffi_request_auth_kind(
    SseDeserializer deserializer,
  );

  @protected
  FfiRequestBody sse_decode_ffi_request_body(SseDeserializer deserializer);

  @protected
  FfiRequestBodyKind sse_decode_ffi_request_body_kind(
    SseDeserializer deserializer,
  );

  @protected
  FfiRequestMethod sse_decode_ffi_request_method(SseDeserializer deserializer);

  @protected
  FfiResponseHeader sse_decode_ffi_response_header(
    SseDeserializer deserializer,
  );

  @protected
  FfiStoredRequest sse_decode_ffi_stored_request(SseDeserializer deserializer);

  @protected
  FfiWorkspace sse_decode_ffi_workspace(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<FfiCollection> sse_decode_list_ffi_collection(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiEnvironment> sse_decode_list_ffi_environment(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiEnvironmentVariable> sse_decode_list_ffi_environment_variable(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiKeyValue> sse_decode_list_ffi_key_value(SseDeserializer deserializer);

  @protected
  List<FfiResponseHeader> sse_decode_list_ffi_response_header(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiStoredRequest> sse_decode_list_ffi_stored_request(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiWorkspace> sse_decode_list_ffi_workspace(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FfiExecutionError? sse_decode_opt_box_autoadd_ffi_execution_error(
    SseDeserializer deserializer,
  );

  @protected
  FfiExecutionResponse? sse_decode_opt_box_autoadd_ffi_execution_response(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_environment_variable(
    FfiEnvironmentVariable self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_execution_error(
    FfiExecutionError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_execution_options(
    FfiExecutionOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_execution_response(
    FfiExecutionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_request(
    FfiRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_api_key_placement(
    FfiApiKeyPlacement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_collection(FfiCollection self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_environment(
    FfiEnvironment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_environment_variable(
    FfiEnvironmentVariable self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_execution_error(
    FfiExecutionError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_execution_error_kind(
    FfiExecutionErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_execution_options(
    FfiExecutionOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_execution_outcome(
    FfiExecutionOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_execution_response(
    FfiExecutionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_key_value(FfiKeyValue self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_request(FfiRequest self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_request_auth(
    FfiRequestAuth self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_request_auth_kind(
    FfiRequestAuthKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_request_body(
    FfiRequestBody self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_request_body_kind(
    FfiRequestBodyKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_request_method(
    FfiRequestMethod self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_response_header(
    FfiResponseHeader self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_stored_request(
    FfiStoredRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_workspace(FfiWorkspace self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_collection(
    List<FfiCollection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_environment(
    List<FfiEnvironment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_environment_variable(
    List<FfiEnvironmentVariable> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_key_value(
    List<FfiKeyValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_response_header(
    List<FfiResponseHeader> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_stored_request(
    List<FfiStoredRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_workspace(
    List<FfiWorkspace> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_execution_error(
    FfiExecutionError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_execution_response(
    FfiExecutionResponse? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class PostKillerRustLibWire implements BaseWire {
  factory PostKillerRustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      PostKillerRustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PostKillerRustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
