// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class PostKillerRustLib
    extends
        BaseEntrypoint<
          PostKillerRustLibApi,
          PostKillerRustLibApiImpl,
          PostKillerRustLibWire
        > {
  @internal
  static final instance = PostKillerRustLib._();

  PostKillerRustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    PostKillerRustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required PostKillerRustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<PostKillerRustLibApiImpl, PostKillerRustLibWire>
  get apiImplConstructor => PostKillerRustLibApiImpl.new;

  @override
  WireConstructor<PostKillerRustLibWire> get wireConstructor =>
      PostKillerRustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 628990917;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'post_killer_ffi_bridge',
        ioDirectory: '../../crates/ffi_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class PostKillerRustLibApi extends BaseApi {
  Future<FfiCollection> crateApiCreateCollection({
    required String workspaceId,
    required String name,
  });

  Future<FfiWorkspace> crateApiCreateWorkspace({required String name});

  Future<FfiExecutionOutcome> crateApiExecuteRequest({
    required FfiRequest request,
  });

  Future<FfiExecutionOutcome> crateApiExecuteRequestWithOptions({
    required FfiRequest request,
    required FfiExecutionOptions options,
  });

  Future<FfiExecutionOptions> crateApiFfiExecutionOptionsDefault();

  Future<List<FfiCollection>> crateApiListCollections({
    required String workspaceId,
  });

  Future<List<FfiStoredRequest>> crateApiListRequests({
    required String collectionId,
  });

  Future<List<FfiWorkspace>> crateApiListWorkspaces();

  Future<FfiStoredRequest> crateApiSaveRequest({
    required String collectionId,
    String? folderId,
    required FfiRequest request,
  });
}

class PostKillerRustLibApiImpl extends PostKillerRustLibApiImplPlatform
    implements PostKillerRustLibApi {
  PostKillerRustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FfiCollection> crateApiCreateCollection({
    required String workspaceId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_collection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateCollectionConstMeta,
        argValues: [workspaceId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateCollectionConstMeta => const TaskConstMeta(
    debugName: "create_collection",
    argNames: ["workspaceId", "name"],
  );

  @override
  Future<FfiWorkspace> crateApiCreateWorkspace({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_workspace,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateWorkspaceConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateWorkspaceConstMeta =>
      const TaskConstMeta(debugName: "create_workspace", argNames: ["name"]);

  @override
  Future<FfiExecutionOutcome> crateApiExecuteRequest({
    required FfiRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ffi_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_execution_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecuteRequestConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecuteRequestConstMeta =>
      const TaskConstMeta(debugName: "execute_request", argNames: ["request"]);

  @override
  Future<FfiExecutionOutcome> crateApiExecuteRequestWithOptions({
    required FfiRequest request,
    required FfiExecutionOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ffi_request(request, serializer);
          sse_encode_box_autoadd_ffi_execution_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_execution_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExecuteRequestWithOptionsConstMeta,
        argValues: [request, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecuteRequestWithOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "execute_request_with_options",
        argNames: ["request", "options"],
      );

  @override
  Future<FfiExecutionOptions> crateApiFfiExecutionOptionsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_execution_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFfiExecutionOptionsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfiExecutionOptionsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_execution_options_default",
        argNames: [],
      );

  @override
  Future<List<FfiCollection>> crateApiListCollections({
    required String workspaceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ffi_collection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListCollectionsConstMeta,
        argValues: [workspaceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListCollectionsConstMeta => const TaskConstMeta(
    debugName: "list_collections",
    argNames: ["workspaceId"],
  );

  @override
  Future<List<FfiStoredRequest>> crateApiListRequests({
    required String collectionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collectionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ffi_stored_request,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListRequestsConstMeta,
        argValues: [collectionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListRequestsConstMeta => const TaskConstMeta(
    debugName: "list_requests",
    argNames: ["collectionId"],
  );

  @override
  Future<List<FfiWorkspace>> crateApiListWorkspaces() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ffi_workspace,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListWorkspacesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListWorkspacesConstMeta =>
      const TaskConstMeta(debugName: "list_workspaces", argNames: []);

  @override
  Future<FfiStoredRequest> crateApiSaveRequest({
    required String collectionId,
    String? folderId,
    required FfiRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(collectionId, serializer);
          sse_encode_opt_String(folderId, serializer);
          sse_encode_box_autoadd_ffi_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_stored_request,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveRequestConstMeta,
        argValues: [collectionId, folderId, request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveRequestConstMeta => const TaskConstMeta(
    debugName: "save_request",
    argNames: ["collectionId", "folderId", "request"],
  );

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FfiExecutionError dco_decode_box_autoadd_ffi_execution_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_execution_error(raw);
  }

  @protected
  FfiExecutionOptions dco_decode_box_autoadd_ffi_execution_options(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_execution_options(raw);
  }

  @protected
  FfiExecutionResponse dco_decode_box_autoadd_ffi_execution_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_execution_response(raw);
  }

  @protected
  FfiRequest dco_decode_box_autoadd_ffi_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_request(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  FfiApiKeyPlacement dco_decode_ffi_api_key_placement(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiApiKeyPlacement.values[raw as int];
  }

  @protected
  FfiCollection dco_decode_ffi_collection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiCollection(
      id: dco_decode_String(arr[0]),
      workspaceId: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
    );
  }

  @protected
  FfiExecutionError dco_decode_ffi_execution_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiExecutionError(
      kind: dco_decode_ffi_execution_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
      field: dco_decode_opt_String(arr[2]),
      limitBytes: dco_decode_opt_CastedPrimitive_u_64(arr[3]),
    );
  }

  @protected
  FfiExecutionErrorKind dco_decode_ffi_execution_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiExecutionErrorKind.values[raw as int];
  }

  @protected
  FfiExecutionOptions dco_decode_ffi_execution_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiExecutionOptions(
      timeoutMillis: dco_decode_CastedPrimitive_u_64(arr[0]),
      maxRedirects: dco_decode_opt_box_autoadd_u_32(arr[1]),
      maxResponseBytes: dco_decode_CastedPrimitive_u_64(arr[2]),
    );
  }

  @protected
  FfiExecutionOutcome dco_decode_ffi_execution_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiExecutionOutcome(
      response: dco_decode_opt_box_autoadd_ffi_execution_response(arr[0]),
      error: dco_decode_opt_box_autoadd_ffi_execution_error(arr[1]),
    );
  }

  @protected
  FfiExecutionResponse dco_decode_ffi_execution_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FfiExecutionResponse(
      requestId: dco_decode_String(arr[0]),
      status: dco_decode_u_16(arr[1]),
      headers: dco_decode_list_ffi_response_header(arr[2]),
      body: dco_decode_list_prim_u_8_strict(arr[3]),
      effectiveUrl: dco_decode_String(arr[4]),
      durationMillis: dco_decode_CastedPrimitive_u_64(arr[5]),
    );
  }

  @protected
  FfiKeyValue dco_decode_ffi_key_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiKeyValue(
      key: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
      enabled: dco_decode_bool(arr[2]),
    );
  }

  @protected
  FfiRequest dco_decode_ffi_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return FfiRequest(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      method: dco_decode_ffi_request_method(arr[2]),
      url: dco_decode_String(arr[3]),
      queryParams: dco_decode_list_ffi_key_value(arr[4]),
      headers: dco_decode_list_ffi_key_value(arr[5]),
      body: dco_decode_ffi_request_body(arr[6]),
      auth: dco_decode_ffi_request_auth(arr[7]),
    );
  }

  @protected
  FfiRequestAuth dco_decode_ffi_request_auth(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FfiRequestAuth(
      kind: dco_decode_ffi_request_auth_kind(arr[0]),
      username: dco_decode_String(arr[1]),
      password: dco_decode_String(arr[2]),
      token: dco_decode_String(arr[3]),
      key: dco_decode_String(arr[4]),
      value: dco_decode_String(arr[5]),
      placement: dco_decode_ffi_api_key_placement(arr[6]),
    );
  }

  @protected
  FfiRequestAuthKind dco_decode_ffi_request_auth_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiRequestAuthKind.values[raw as int];
  }

  @protected
  FfiRequestBody dco_decode_ffi_request_body(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiRequestBody(
      kind: dco_decode_ffi_request_body_kind(arr[0]),
      content: dco_decode_String(arr[1]),
      contentType: dco_decode_opt_String(arr[2]),
      fields: dco_decode_list_ffi_key_value(arr[3]),
    );
  }

  @protected
  FfiRequestBodyKind dco_decode_ffi_request_body_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiRequestBodyKind.values[raw as int];
  }

  @protected
  FfiRequestMethod dco_decode_ffi_request_method(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiRequestMethod.values[raw as int];
  }

  @protected
  FfiResponseHeader dco_decode_ffi_response_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiResponseHeader(
      name: dco_decode_String(arr[0]),
      value: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  FfiStoredRequest dco_decode_ffi_stored_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiStoredRequest(
      collectionId: dco_decode_String(arr[0]),
      folderId: dco_decode_opt_String(arr[1]),
      request: dco_decode_ffi_request(arr[2]),
    );
  }

  @protected
  FfiWorkspace dco_decode_ffi_workspace(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiWorkspace(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<FfiCollection> dco_decode_list_ffi_collection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_collection).toList();
  }

  @protected
  List<FfiKeyValue> dco_decode_list_ffi_key_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_key_value).toList();
  }

  @protected
  List<FfiResponseHeader> dco_decode_list_ffi_response_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_response_header).toList();
  }

  @protected
  List<FfiStoredRequest> dco_decode_list_ffi_stored_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_stored_request).toList();
  }

  @protected
  List<FfiWorkspace> dco_decode_list_ffi_workspace(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_workspace).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_u_64(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FfiExecutionError? dco_decode_opt_box_autoadd_ffi_execution_error(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ffi_execution_error(raw);
  }

  @protected
  FfiExecutionResponse? dco_decode_opt_box_autoadd_ffi_execution_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_ffi_execution_response(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FfiExecutionError sse_decode_box_autoadd_ffi_execution_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_execution_error(deserializer));
  }

  @protected
  FfiExecutionOptions sse_decode_box_autoadd_ffi_execution_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_execution_options(deserializer));
  }

  @protected
  FfiExecutionResponse sse_decode_box_autoadd_ffi_execution_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_execution_response(deserializer));
  }

  @protected
  FfiRequest sse_decode_box_autoadd_ffi_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_request(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  FfiApiKeyPlacement sse_decode_ffi_api_key_placement(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiApiKeyPlacement.values[inner];
  }

  @protected
  FfiCollection sse_decode_ffi_collection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_workspaceId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return FfiCollection(
      id: var_id,
      workspaceId: var_workspaceId,
      name: var_name,
    );
  }

  @protected
  FfiExecutionError sse_decode_ffi_execution_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_ffi_execution_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_field = sse_decode_opt_String(deserializer);
    var var_limitBytes = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    return FfiExecutionError(
      kind: var_kind,
      message: var_message,
      field: var_field,
      limitBytes: var_limitBytes,
    );
  }

  @protected
  FfiExecutionErrorKind sse_decode_ffi_execution_error_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiExecutionErrorKind.values[inner];
  }

  @protected
  FfiExecutionOptions sse_decode_ffi_execution_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeoutMillis = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_maxRedirects = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_maxResponseBytes = sse_decode_CastedPrimitive_u_64(deserializer);
    return FfiExecutionOptions(
      timeoutMillis: var_timeoutMillis,
      maxRedirects: var_maxRedirects,
      maxResponseBytes: var_maxResponseBytes,
    );
  }

  @protected
  FfiExecutionOutcome sse_decode_ffi_execution_outcome(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_response = sse_decode_opt_box_autoadd_ffi_execution_response(
      deserializer,
    );
    var var_error = sse_decode_opt_box_autoadd_ffi_execution_error(
      deserializer,
    );
    return FfiExecutionOutcome(response: var_response, error: var_error);
  }

  @protected
  FfiExecutionResponse sse_decode_ffi_execution_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_requestId = sse_decode_String(deserializer);
    var var_status = sse_decode_u_16(deserializer);
    var var_headers = sse_decode_list_ffi_response_header(deserializer);
    var var_body = sse_decode_list_prim_u_8_strict(deserializer);
    var var_effectiveUrl = sse_decode_String(deserializer);
    var var_durationMillis = sse_decode_CastedPrimitive_u_64(deserializer);
    return FfiExecutionResponse(
      requestId: var_requestId,
      status: var_status,
      headers: var_headers,
      body: var_body,
      effectiveUrl: var_effectiveUrl,
      durationMillis: var_durationMillis,
    );
  }

  @protected
  FfiKeyValue sse_decode_ffi_key_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    return FfiKeyValue(key: var_key, value: var_value, enabled: var_enabled);
  }

  @protected
  FfiRequest sse_decode_ffi_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_method = sse_decode_ffi_request_method(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_queryParams = sse_decode_list_ffi_key_value(deserializer);
    var var_headers = sse_decode_list_ffi_key_value(deserializer);
    var var_body = sse_decode_ffi_request_body(deserializer);
    var var_auth = sse_decode_ffi_request_auth(deserializer);
    return FfiRequest(
      id: var_id,
      name: var_name,
      method: var_method,
      url: var_url,
      queryParams: var_queryParams,
      headers: var_headers,
      body: var_body,
      auth: var_auth,
    );
  }

  @protected
  FfiRequestAuth sse_decode_ffi_request_auth(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_ffi_request_auth_kind(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    var var_placement = sse_decode_ffi_api_key_placement(deserializer);
    return FfiRequestAuth(
      kind: var_kind,
      username: var_username,
      password: var_password,
      token: var_token,
      key: var_key,
      value: var_value,
      placement: var_placement,
    );
  }

  @protected
  FfiRequestAuthKind sse_decode_ffi_request_auth_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiRequestAuthKind.values[inner];
  }

  @protected
  FfiRequestBody sse_decode_ffi_request_body(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_ffi_request_body_kind(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_contentType = sse_decode_opt_String(deserializer);
    var var_fields = sse_decode_list_ffi_key_value(deserializer);
    return FfiRequestBody(
      kind: var_kind,
      content: var_content,
      contentType: var_contentType,
      fields: var_fields,
    );
  }

  @protected
  FfiRequestBodyKind sse_decode_ffi_request_body_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiRequestBodyKind.values[inner];
  }

  @protected
  FfiRequestMethod sse_decode_ffi_request_method(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiRequestMethod.values[inner];
  }

  @protected
  FfiResponseHeader sse_decode_ffi_response_header(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_value = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiResponseHeader(name: var_name, value: var_value);
  }

  @protected
  FfiStoredRequest sse_decode_ffi_stored_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_collectionId = sse_decode_String(deserializer);
    var var_folderId = sse_decode_opt_String(deserializer);
    var var_request = sse_decode_ffi_request(deserializer);
    return FfiStoredRequest(
      collectionId: var_collectionId,
      folderId: var_folderId,
      request: var_request,
    );
  }

  @protected
  FfiWorkspace sse_decode_ffi_workspace(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return FfiWorkspace(id: var_id, name: var_name);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<FfiCollection> sse_decode_list_ffi_collection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiCollection>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_collection(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiKeyValue> sse_decode_list_ffi_key_value(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiKeyValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_key_value(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiResponseHeader> sse_decode_list_ffi_response_header(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiResponseHeader>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_response_header(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiStoredRequest> sse_decode_list_ffi_stored_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiStoredRequest>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_stored_request(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiWorkspace> sse_decode_list_ffi_workspace(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiWorkspace>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_workspace(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FfiExecutionError? sse_decode_opt_box_autoadd_ffi_execution_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ffi_execution_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FfiExecutionResponse? sse_decode_opt_box_autoadd_ffi_execution_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ffi_execution_response(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ffi_execution_error(
    FfiExecutionError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_execution_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_execution_options(
    FfiExecutionOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_execution_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_execution_response(
    FfiExecutionResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_execution_response(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_request(
    FfiRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_ffi_api_key_placement(
    FfiApiKeyPlacement self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_collection(FfiCollection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.workspaceId, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_ffi_execution_error(
    FfiExecutionError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_execution_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.field, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.limitBytes, serializer);
  }

  @protected
  void sse_encode_ffi_execution_error_kind(
    FfiExecutionErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_execution_options(
    FfiExecutionOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.timeoutMillis, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxRedirects, serializer);
    sse_encode_CastedPrimitive_u_64(self.maxResponseBytes, serializer);
  }

  @protected
  void sse_encode_ffi_execution_outcome(
    FfiExecutionOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_ffi_execution_response(
      self.response,
      serializer,
    );
    sse_encode_opt_box_autoadd_ffi_execution_error(self.error, serializer);
  }

  @protected
  void sse_encode_ffi_execution_response(
    FfiExecutionResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.requestId, serializer);
    sse_encode_u_16(self.status, serializer);
    sse_encode_list_ffi_response_header(self.headers, serializer);
    sse_encode_list_prim_u_8_strict(self.body, serializer);
    sse_encode_String(self.effectiveUrl, serializer);
    sse_encode_CastedPrimitive_u_64(self.durationMillis, serializer);
  }

  @protected
  void sse_encode_ffi_key_value(FfiKeyValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
    sse_encode_bool(self.enabled, serializer);
  }

  @protected
  void sse_encode_ffi_request(FfiRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_ffi_request_method(self.method, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_list_ffi_key_value(self.queryParams, serializer);
    sse_encode_list_ffi_key_value(self.headers, serializer);
    sse_encode_ffi_request_body(self.body, serializer);
    sse_encode_ffi_request_auth(self.auth, serializer);
  }

  @protected
  void sse_encode_ffi_request_auth(
    FfiRequestAuth self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_request_auth_kind(self.kind, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
    sse_encode_ffi_api_key_placement(self.placement, serializer);
  }

  @protected
  void sse_encode_ffi_request_auth_kind(
    FfiRequestAuthKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_request_body(
    FfiRequestBody self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_request_body_kind(self.kind, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_opt_String(self.contentType, serializer);
    sse_encode_list_ffi_key_value(self.fields, serializer);
  }

  @protected
  void sse_encode_ffi_request_body_kind(
    FfiRequestBodyKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_request_method(
    FfiRequestMethod self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_response_header(
    FfiResponseHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_prim_u_8_strict(self.value, serializer);
  }

  @protected
  void sse_encode_ffi_stored_request(
    FfiStoredRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.collectionId, serializer);
    sse_encode_opt_String(self.folderId, serializer);
    sse_encode_ffi_request(self.request, serializer);
  }

  @protected
  void sse_encode_ffi_workspace(FfiWorkspace self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_ffi_collection(
    List<FfiCollection> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_collection(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_key_value(
    List<FfiKeyValue> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_key_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_response_header(
    List<FfiResponseHeader> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_response_header(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_stored_request(
    List<FfiStoredRequest> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_stored_request(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_workspace(
    List<FfiWorkspace> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_workspace(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(
    int? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ffi_execution_error(
    FfiExecutionError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ffi_execution_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ffi_execution_response(
    FfiExecutionResponse? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ffi_execution_response(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
